-- liquibase formatted sql

-- changeset template:orders-schema-1
CREATE TABLE customer (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(120) NOT NULL,
   email VARCHAR(200),
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset template:orders-schema-2
CREATE TABLE product (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(120) NOT NULL,
   sku VARCHAR(60) NOT NULL,
   price NUMERIC(14,2) NOT NULL,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT uq_product_sku UNIQUE (sku)
);

-- changeset template:orders-schema-3
CREATE TABLE orders (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id BIGINT NOT NULL,
   status VARCHAR(40) NOT NULL,
   order_total NUMERIC(14,2) NOT NULL,
   createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modifydate TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- changeset template:orders-schema-4
CREATE TABLE order_line (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   order_id BIGINT NOT NULL,
   product_id BIGINT NOT NULL,
   quantity INTEGER NOT NULL,
   unit_price NUMERIC(14,2) NOT NULL,
   line_total NUMERIC(14,2) NOT NULL,
   notes VARCHAR(255)
);

-- changeset template:orders-schema-5
ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customer (id);
ALTER TABLE order_line ADD CONSTRAINT fk_order_line_order FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_line ADD CONSTRAINT fk_order_line_product FOREIGN KEY (product_id) REFERENCES product (id);

